// Generated by gencpp from file tt5_ros/Encoders.msg
// DO NOT EDIT!


#ifndef TT5_ROS_MESSAGE_ENCODERS_H
#define TT5_ROS_MESSAGE_ENCODERS_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace tt5_ros
{
template <class ContainerAllocator>
struct Encoders_
{
  typedef Encoders_<ContainerAllocator> Type;

  Encoders_()
    : encoder1(0)
    , encoder2(0)
    , encoder3(0)
    , encoder4(0)  {
    }
  Encoders_(const ContainerAllocator& _alloc)
    : encoder1(0)
    , encoder2(0)
    , encoder3(0)
    , encoder4(0)  {
  (void)_alloc;
    }



   typedef int32_t _encoder1_type;
  _encoder1_type encoder1;

   typedef int32_t _encoder2_type;
  _encoder2_type encoder2;

   typedef int32_t _encoder3_type;
  _encoder3_type encoder3;

   typedef int32_t _encoder4_type;
  _encoder4_type encoder4;




  typedef boost::shared_ptr< ::tt5_ros::Encoders_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::tt5_ros::Encoders_<ContainerAllocator> const> ConstPtr;

}; // struct Encoders_

typedef ::tt5_ros::Encoders_<std::allocator<void> > Encoders;

typedef boost::shared_ptr< ::tt5_ros::Encoders > EncodersPtr;
typedef boost::shared_ptr< ::tt5_ros::Encoders const> EncodersConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::tt5_ros::Encoders_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::tt5_ros::Encoders_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace tt5_ros

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'tt5_ros': ['/home/brian/Spherical-Tensegrity/ROS/src/tt5_ros/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::tt5_ros::Encoders_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::tt5_ros::Encoders_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::tt5_ros::Encoders_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::tt5_ros::Encoders_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::tt5_ros::Encoders_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::tt5_ros::Encoders_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::tt5_ros::Encoders_<ContainerAllocator> >
{
  static const char* value()
  {
    return "2a122a8533e2dea8296bced774e43ca1";
  }

  static const char* value(const ::tt5_ros::Encoders_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x2a122a8533e2dea8ULL;
  static const uint64_t static_value2 = 0x296bced774e43ca1ULL;
};

template<class ContainerAllocator>
struct DataType< ::tt5_ros::Encoders_<ContainerAllocator> >
{
  static const char* value()
  {
    return "tt5_ros/Encoders";
  }

  static const char* value(const ::tt5_ros::Encoders_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::tt5_ros::Encoders_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 encoder1\n\
int32 encoder2\n\
int32 encoder3\n\
int32 encoder4\n\
";
  }

  static const char* value(const ::tt5_ros::Encoders_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::tt5_ros::Encoders_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.encoder1);
      stream.next(m.encoder2);
      stream.next(m.encoder3);
      stream.next(m.encoder4);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Encoders_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::tt5_ros::Encoders_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::tt5_ros::Encoders_<ContainerAllocator>& v)
  {
    s << indent << "encoder1: ";
    Printer<int32_t>::stream(s, indent + "  ", v.encoder1);
    s << indent << "encoder2: ";
    Printer<int32_t>::stream(s, indent + "  ", v.encoder2);
    s << indent << "encoder3: ";
    Printer<int32_t>::stream(s, indent + "  ", v.encoder3);
    s << indent << "encoder4: ";
    Printer<int32_t>::stream(s, indent + "  ", v.encoder4);
  }
};

} // namespace message_operations
} // namespace ros

#endif // TT5_ROS_MESSAGE_ENCODERS_H
